version: '3'
services:
  backend:
      container_name: flask
      build: ./backend
      volumes:
          - type: bind
            source: ./backend/app
            target: /app
      ports:
          - "5001:5001"
      # command: flask run --host 0.0.0.0 --port 5000
      environment:
          - FLASK_DEBUG=1
          - FLASK_ENV=development
      tty: true
      # privileged: true
      links:
          - database

  database:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: izawa
      MYSQL_PASSWORD: izawa
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    tty: true
    stdin_open: true
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/sqls:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306