CREATE TABLE IF NOT EXISTS Spend(
    id INT AUTO_INCREMENT PRIMARY KEY,
    spend_name VARCHAR(128) NOT NULL,
    -- price int(6) NOT NULL,
    pic VARCHAR(32) NOT NULL,
    FOREIGN KEY fk_pic(pic) REFERENCES User(name) ON DELETE CASCADE ON UPDATE CASCADE,
);